name: "CI pipeline"

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: "read"

concurrency:
  group: "ci-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:

  composer:
    name: "Composer config validation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Validate composer.json"
        run: "composer validate --strict"

  php:
    name: "PHP ${{ matrix.php-version }} (${{ matrix.dependencies }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        dependencies:
          - "default"
        include:
          - php-version: "8.1"
            dependencies: "lowest"
    steps:
      - name: "git checkout"
        uses: "actions/checkout@v7"
        with:
          persist-credentials: false
      - name: "setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "json"
          coverage: "xdebug"
          tools: "composer:v2"
      - name: "install composer dependencies (default)"
        if: "matrix.dependencies == 'default'"
        run: "composer install --prefer-dist --no-interaction --no-progress --ignore-platform-req=ext-sapnwrfc"
      - name: "install composer dependencies (lowest)"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --prefer-lowest --prefer-dist --no-interaction --no-progress --ignore-platform-req=ext-sapnwrfc"
      - name: "audit dependencies for known security vulnerabilities"
        if: "matrix.php-version == '8.1'"
        run: "composer audit"
